dist: trusty
sudo: required
# this image requires a lot of space to build, it seems generally the
# VMs have ~3GB of space only :/ it seems to vary from build to build
# though, try the minimal image to eek out as much space as i can
language: minimal
services:
  - docker

script:
  - bin/ci

notifications:
  slack:
    secure: UaTY60y0S+3JDU7G9nkFMnkib+pDrn6JqwmIgNoDYAd8/GuwwvUiuGAJKnBjoR4839VHBtdsRjRA1u0r6vt+lXHJ9zVM+gGcYSGkqoxKv1ciDiWvRF4x//I1mp/l/e7O49+rwNGa/qAF4HE+mkY12Ga7jlds7XRmnqVYjflCFL9JMH9oXicWlFsgGzt55lmi7oMZwxviiF7SzNBakfBk4rAC/ZLEbu4sj4EnZ6hXj3wjxFT/YAgOUQD99oWk2bOQ6jUByiadJjYremzLD8PQ2RtBw3ZD41YHFTwDc7rST85XxltGy9u6/ugaifkb9H2lBKBKrodUWhOKymh3cmG27lhRLtYxy/jvaLO1GlMsoCPfyyhObkJvbF6lyymAqCh0XCOOFSbgRaNnX+XGavVVWYDB+HUxEQOL63zpyYZXHQ4cwAfwoD8Ba1XlhkVq6BxTvL2yKXUhVIK3jUwM4oqIhW8TMCLE0W7mdHz89U+W1Vp4kaJDQzUxH70AlvVWTyLqQit5KgKWrrBb3cyZQvA0GDKSmefaD2PNU3Qy/Oma/gUU4c32b8y1Rkp78y3BlT8Uo1RSlS1D/poulqR7Tr9LF9hVCfN7sGdNZw/paCVwAPyvewp2hsVrTcphefglqSAOBQjBCPxzO7/cnhn/dPQQpNfdt6nOJpM5jvomcRMuMpg=
